### ISSUE TITLE
perf rpm missing libperf-jvmti.so

### ISSUE THREAD

**Issue by tetsuzawa** [aws/aws-graviton-getting-started#119]
I'm trying to analyze the performance of an application written in scala running on Graviton2 using the [Profiling Java applications](https://github.com/aws/aws-graviton-getting-started/blob/main/java.md#profiling-java-applications).

However, there is no libperf-jvmti.so in perf rpm.
Is there any way to install libperf-jvmti.so?

AMI: amzn2-ami-hvm-2.0.20210525.0-arm64-gp2
Instance Type: t4g.large
perf package: perf-4.14.232-176.381.amzn2.aarch64

Thank you.

**Comment by tetsuzawa** [comment]
I installed perf simply with the following command.

```
sudo yum install -y perf
```

**Comment by geoffreyblake** [comment]
We will make sure AL2 fixes this omission.  But in the meantime, you can build it yourself if you're so inclined by the following steps on AL2, which we'll also add to this guide:

```shell
cd $HOME
sudo yumdownloader --source kernel

cat > .rpmmacros << __EOF__
%_topdir    %(echo $HOME)/kernel-source
__EOF__

rpm -ivh ./kernel-*.amzn2.src.rpm
sudo yum-builddep kernel
cd kernel-source/SPECS
rpmbuild -bp kernel.spec

cd ../BUILD
cd kernel-*.amzn2
cd linux-*.amzn2.aarch64
cd tools/perf
make
```

That should produce a libperf-jvmti.so binary specific to your AL2 install.

**Comment by tetsuzawa** [comment]
@geoffreyblake 
Thank you for your quick response.

The above steps worked correctly, but in order to generate libperf-jvmti.so, I needed to install jdk before running that.

I installed the corretto8 by the following command.

```shell
sudo amazon-linux-extras enable corretto8
sudo yum install -y java-1.8.0-amazon-corretto-devel
```

**Comment by geoffreyblake** [comment]
#126 submitted to add the libperf-jvmti instructions to the Java section of the guid.
