### ISSUE TITLE
MongoDB - building from source still required?

### ISSUE THREAD

**Issue by dhendo** [aws/aws-graviton-getting-started#145]
Is the note in https://github.com/aws/aws-graviton-getting-started/blob/main/README.md#recent-software-updates-relevant-to-graviton regarding mongodb and LSE locks still valid, given what looks like a backport in 4.9.0, 4.2.13, 4.4.5

https://jira.mongodb.org/browse/SERVER-51722

It looks like 4.4.7+ may have LSE enable due to the use of an upgraded compiler.
https://jira.mongodb.org/browse/SERVER-56237

The 5.x builds look to target armv8.2-a by default anyway:
https://jira.mongodb.org/browse/SERVER-56347

**Comment by AGSaidi** [comment]
Yes, you're correct. Would you like to send a PR to update it?

**Comment by dhendo** [comment]
Will do
