### ISSUE TITLE
Tensorflow install error

### ISSUE THREAD

**Issue by keithyau** [aws/aws-graviton-getting-started#155]
![image](https://user-images.githubusercontent.com/659311/135020074-29f0c631-9d5e-4a84-892b-b34faf5bcea0.png)

cd $HOME/tensorflow/tensorflow/examples/label_image/data
wget https://storage.googleapis.com/download.tensorflow.org/models/inception_v3_2016_08_28_frozen.pb.tar.gz
tar xf inception_v3_2016_08_28_frozen.pb.tar.gz
cd $HOME/tensorflow
bazel build --config=opt --copt=-O3 --copt=-march=armv8.2-a+fp16+rcpc+dotprod+crypto --copt=-flax-vector-conversions tensorflow/examples/label_image/...
bazel-bin/tensorflow/examples/label_image/label_image

**Comment by snadampal** [comment]
Please refer to the ArmToolSolutions github for building the latest version of Tensorflow for Graviton cores.
https://github.com/ARM-software/Tool-Solutions/blob/master/docker/tensorflow-aarch64/scripts/build-tensorflow.sh

Here are the docker images for Graviton with TF 2.7:
https://hub.docker.com/r/armswdev/tensorflow-arm-neoverse

**Comment by snadampal** [comment]
@keithyau , please let us know if you are looking for any further support on this issue.
