### ISSUE TITLE
sysstat version installed by perfrunbook for AL2 is too old

### ISSUE THREAD

**Issue by geoffreyblake** [aws/aws-graviton-getting-started#173]
AL2 uses sysstat v10.1.5, but the perfrunbook uses features from later versions of sysstat.  Perfrunbook needs to automate installing the proper version of sysstat on AL2.  Trying to use --stat all-irqs fails on AL2 for `./measure_and_plot_basic_sysstat_stats.py`.

**Comment by aldredb** [comment]
any updates on this? Can't run the script `measure_and_plot_basic_sysstat_stats.py` due this issue and using Amazon Linux 2022 is not supported yet based on https://github.com/aws/aws-graviton-getting-started/blob/main/perfrunbook/utilities/install_perfrunbook_dependencies.sh

**Comment by RamaMalladiAWS** [comment]
@geoffreyblake , any update on this one? Should we close it? Thanks

**Comment by geoffreyblake** [comment]
AL2023 should be supported now, but this has not been fixed on AL2 yet.

**Comment by geoffreyblake** [comment]
We have a new tool that can be used in place of the simpler scripts: https://github.com/aws/aperf. 
Can close this as no longer required.
