### ISSUE TITLE
pycld2 Python package not supported with Graviton2

### ISSUE THREAD

**Issue by doronbl** [aws/aws-graviton-getting-started#181]
Seems that https://pypi.org/project/pycld2/ is not supported on Graviton2.

**Comment by AWSjswinney** [comment]
I will open an issue against that project to ask them to add support for aarch64 builds.

**Comment by AWSjswinney** [comment]
As a work around, it appears that the latest version will build and install on Ubuntu focal:

```
sudo apt update && sudo apt install build-essential python3-pip
git clone https://github.com/aboSamoor/pycld2.git
cd pycld2
python3 setup.py install
cd ..
echo "import pycl2" | python3
```

**Comment by AWSjswinney** [comment]
It also appears that the original maintainer of the project has abandoned it. There are some suggestions in this issue: https://github.com/aboSamoor/pycld2/issues/39
