### ISSUE TITLE
Add More Detail to ElastiCache

### ISSUE THREAD

**Issue by razorsedge** [aws/aws-graviton-getting-started#195]
In the `managed_services.md` document, in the "Amazon ElastiCache" section, add an additional link to https://aws.amazon.com/about-aws/whats-new/2021/11/amazon-elasticache-supports-t4g-graviton2-based-instances/ to cover support for more instance types.

I had originally thought that only certain instance types (cache.m6g and cache.r6g) were supported.  The additional blog post covers additional cache.t4g types.

**Comment by snadampal** [comment]
Hi @razorsedge thanks for highlighting this, we will update the document.

**Comment by sebpop** [comment]
https://github.com/aws/aws-graviton-getting-started/pull/196

**Comment by sebpop** [comment]
Fixed.
