### ISSUE TITLE
gcc with -m64 flag -- unknow error

### ISSUE THREAD

**Issue by sendtopms** [aws/aws-graviton-getting-started#202]
I am trying to build forked leveldb which has gcc flag -m64. It could not compile due to flag unknown. But the same is compiling on M1 Macbook Air. Will it be included in the next build? Otherwise it would have been major change in multiple repo.

**Comment by sendtopms** [comment]
I tried on Ubuntu 20.04 (gcc version is 9.4)
"gcc -m64 a.c"

**Comment by sendtopms** [comment]
gcc with "-m64" on m1 macbook air is working (no rosatta 2 enabled).

**Comment by AGSaidi** [comment]
Mac OS aliases `gcc` to `clang`. The clang compiler does recognize `-m64` on multiple architectures.

For example:
```
❯ gcc --version
Configured with: --prefix=/Library/Developer/CommandLineTools/usr --with-gxx-include-dir=/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/c++/4.2.1
Apple clang version 13.0.0 (clang-1300.0.29.30)
Target: arm64-apple-darwin20.6.0
```

You could try to build the project using clang istead, but it it would be best to find

**Comment by AWSjswinney** [comment]
@sendtopms Do you still need help with this issue?
