### ISSUE TITLE
Palo Alto Networks/Prisma Cloud support

### ISSUE THREAD

**Issue by corey-cole** [aws/aws-graviton-getting-started#212]
[Prisma Cloud](https://docs.paloaltonetworks.com/prisma/prisma-cloud/prisma-cloud-admin-compute/install/system_requirements) cannot scan arm64 images or run as a Defender sidecar for same.  While there are solutions for customers who are evaluating solutions in this space, it would be great to push Palo Alto to support arm64 for customers who are wedded to this vendor.

**Comment by AGSaidi** [comment]
We regularly ask ISVs to support Graviton, but the best way to convince an ISV to support functionality is for paying customers to ask them for it. If you are a paying customer of theirs, please do ask.
