### ISSUE TITLE
Request: Publish ARM64 Istio Proxy image 

### ISSUE THREAD

**Issue by hfkang** [aws/aws-graviton-getting-started#213]
I'm interested in using graviton, but our infrastructure relies on istio proxy. The current workaround of [building the container](https://github.com/aws/aws-graviton-getting-started/blob/main/containers-workarounds.md) isn't viable at the moment - would it be feasible for a prebuilt image to be published? It would reduce adoption friction significantly!

**Comment by otterley** [comment]
Hi! Thanks for letting us know you're interested! Rest assured we are working with the Istio team on producing a set of native Docker containers for the arm64 architecture. You can join our efforts in the #test-and-release channel in the [Istio Slack community](https://istio.slack.com).
