### ISSUE TITLE
Performance Benchmarking Result of Quant Calculations in Graviton is worse compared to Non-Graviton

### ISSUE THREAD

**Issue by tohwsw** [aws/aws-graviton-getting-started#214]
Hi, we were trying to do a benchmarking on Graviton (c6g.2xlarge) vs non-Graviton (c5.2xlarge) and it seems that calculations on Graviton is slower than it's non-Graviton counterpart. The setup:

    Compiled C++ code from https://www.quantstart.com/articles/Asian-option-pricing-with-C-via-Monte-Carlo-Methods/
    GCC 11.2.1
    Amazon Linux 2022

Here are the flame graph of the two runs.
![perf-c6g](https://user-images.githubusercontent.com/13896741/167371737-c844a97a-ee94-4d05-8e01-c7fb1441cf65.svg)
![perf -c5](https://user-images.githubusercontent.com/13896741/167371763-13b0ad06-2ee6-433d-9537-ab6b8477c6db.svg)

From the graphs it seems the function calc_path_spot_prices is taking more time in Graviton. So I had a look and realised the function is using exp in the calculations. Is the math library not optimized on ARM? How can we optimize the math routines?

Thanks for your help.

**Comment by sebpop** [comment]
Please add clear steps on how to reproduce your performance measurements.

The flamegraphs do not carry useful information: there are very few functions with the same name on the profiles.  linux-perf needs to only measure the compute process, and not the whole system.  One of the flamegraphs shows more than 90% of the time in `do_idle`.

**Comment by tohwsw** [comment]
Hi Sebastian, uploading the code here with a makefile included. The program is short so it takes about 2-3s to complete.
[quantasianoptionpricing.zip](https://github.com/aws/aws-graviton-getting-started/files/8684463/quantasianoptionpricing.zip)
