### ISSUE TITLE
Missing GCC libquadmath

### ISSUE THREAD

**Issue by lubao** [aws/aws-graviton-getting-started#216]
Missing libquadmath on Graviton2 cause following error while compiling the source code based on [boost library](https://www.boost.org/) .
`quadmath.h: No such file or directory` 

It is because of that the [float128.hpp](https://github.com/alisw/boost/blob/master/boost/multiprecision/float128.hpp) from boost library has dependency on "quadmath.h" from GCC.

However, GCC won't compile libquadmath on aarch64 architecture since it already support `long double` data type. As suggestion in [bug report](https://gcc.gnu.org/bugzilla/show_bug.cgi?id=96016), it is recommended to use  `tgmath.h` instead of `quadmath.h`. However, it seems boost library doesn't support `tgmath.h` yet.

Based on the patch attached in bug reported mentioned above, it is possible compile libquadmath on Graviton2 to resolve the issue. [This repo](https://github.com/lubao/arm64v8/tree/main/missing_quadmath) contains information to compile libquadmath on Graviton2 for GCC 9.4.

I would like to contribute the content to this repo. Before I am doing so, could you give me some opinions?

Thanks in advance.

**Comment by sebpop** [comment]
libquadmath is not needed on arm64.  See https://gcc.gnu.org/bugzilla/show_bug.cgi?id=96016
