### ISSUE TITLE
[golang] Graviton2 lambda has problem running CGO enabled code

### ISSUE THREAD

**Issue by hangxie** [aws/aws-graviton-getting-started#248]
Code as below:
```
package main

import (
	"context"
	"fmt"

	"github.com/aws/aws-lambda-go/lambda"
)

func main() {
	lambda.Start(LambdaHandler)
}

func LambdaHandler(ctx context.Context) error {
	fmt.Println("hello, world")
	return nil
}
```

Build with `CGO_ENABLED=1 go build -race -o bootstrap .` under a Graviton2 EC2 instance (you can cross-compile but this makes things less complicated), run `bootstrap` on the EC2 instance with help of RIE (https://docs.aws.amazon.com/lambda/latest/dg/images-test.html) without problem, however, if I run it as a lambda with provided.al2+arm64, it reports:

> FATAL: ThreadSanitizer: unsupported VMA range
> FATAL: Found 39 - Supported 48

I know this may be a go specific problem, but I need to prepare steps to reproduce this before I report this to go community and we need a way to reproduce this problem under EC2 where people can debug.

I've opened a support ticket to AWS (10781433961) asking what's the difference between an EC2 instance and a Lambda that both are Graviton2 based, while the ticket is being worked on, I think I'd better share the issue here as well to get more eyes for both potential solution and awareness.

**Comment by wash-amzn** [comment]
Related: https://github.com/golang/go/issues/29948

**Comment by hangxie** [comment]
I did read that but I'd expect the behavior to be consistent, ie if it happens to lambda then it should happen to EC2 as well, unless Lambda and EC2 use totally different arch, and someone from AWS may be able to answer this question.

**Comment by AGSaidi** [comment]
The number of bits used by a virtual address is a kernel configuration option.

**Comment by hangxie** [comment]
> The number of bits used by a virtual address is a kernel configuration option.

Got it, so it means lambda may not use same kernel as EC2, I can close this issue if someone can confirm this.

**Comment by hangxie** [comment]
It is working in several AWS regions now, I don't think I can provide any details though.
