### ISSUE TITLE
Latency Improvement numbers are not matching for common models like BERT when benchmarking graviton vs intel

### ISSUE THREAD

**Issue by vinayaktrivedi** [aws/aws-graviton-getting-started#263]
We have started benchmarking latency for inference on common huggingface models like BERT, DistilBERT. We are running two pods, one on graviton node (**c7g.4xlarge**) and another on intel node (**c6i.8xlarge**). Both have 1 CPU as request and limit, 6GB of memory as request and limit. For same RPS, we are getting around **20-30%** less latency on graviton pod compared to Intel. Standard benchmarking practices are followed to keep both setups identical in all other aspects. 

Some details how we created graviton pod. 
1. We used the base image "_armswdev/pytorch-arm-neoverse:r22.10-torch-1.12.0-onednn-acl_" as mentioned in [https://github.com/aws/aws-graviton-getting-started/blob/main/machinelearning/pytorch.md](https://github.com/aws/aws-graviton-getting-started/blob/main/machinelearning/pytorch.md). We install all the needed dependencies which are compatible with aarch64 architecture and are recommended version here  https://github.com/aws/aws-graviton-getting-started/. More specifically the versions of common dependencies are: 

      a) numpy==1.21.5
      b) pandas==1.1.3
      c) transformers==4.23.1
      d) scikit-learn==1.1.3
      e) Keras==2.6.0
 
2. We followed the steps in this guide https://github.com/aws-samples/aws-graviton-ml-inference-armnn-example/tree/main/src/Dockerfile to install "pyarmnn" version 30.0.0
3. We enabled the flag export DNNL_DEFAULT_FPMATH_MODE=BF16. Huge pages and OMP_NUM_THREADS are not updated since these are not present in intel setup too for basic numbers comparison (Since the first step is to see the performance gain which we get using bf16 and other hardware improvements introduced in graviton). 

------
As suggested in https://github.com/aws/aws-graviton-getting-started/blob/main/machinelearning/pytorch.md, we turned on the debug mode logs using DNNL_VERBOSE and OMP_DISPLAY_ENV variables. Upon logs investigation, it looks ACL GEMM kernels are not being used instead CPP ref is being used. 

<img width="1676" alt="Screenshot 2023-01-13 at 3 50 18 PM" src="https://user-images.githubusercontent.com/25333601/212305616-d0de5fe4-d7f0-4cb6-9a94-afffd4f8cc52.png">

Required libraries are installed in the system namely - **"pyarmnn", "armnn-latest-cpu", "python3-pyarmnn".** 
These similar logs are printed when we run our in-house model pipeline and when we run BERT Benchmark using MLPerf as suggested in getting started guide. 
Attached is the screenshot of logs in production system and notebook [graviton_basic_exp.txt](https://github.com/aws/aws-graviton-getting-started/files/10410881/graviton_basic_exp.txt) shows basic steps taken to run BERT Benchmark using MLPerf. 

------
When trying to use pyarmnn library to load and do inference using resent model on top of above pytorch docker image, in order to see if that logs ACL GEMM Kernels being used, the notebook kernel exits abruptly, indicating runtime issue with the setup. Steps and code was taken from aws-samples repo here: https://github.com/aws-samples/aws-graviton-ml-inference-armnn-example/tree/main/src. Code for same is included in [pyarmnn_exp.txt](https://github.com/aws/aws-graviton-getting-started/files/10410910/pyarmnn_exp.txt).

Please help us in understanding if some config/setup is missing. At the end of the day, we want the latency numbers of graviton after using bf16 acl gemm kernels to be better than intel as claimed in AWS reinvent. 
Thanks.

**Comment by snadampal** [comment]
Hi @vinayaktrivedi, thanks for the details, couple of questions to understand your configuration better: why are you comparing c7g.**4xl** vs c6i.**8xl**? what do you mean by both having 1CPU as request and limit?
> We are running two pods, one on graviton node (c7g.4xlarge) and another on intel node (c6i.8xlarge). Both have 1 CPU as request and limit, 6GB of memory as request and limit. 

We will review the notebook you shared and get back.

**Comment by vinayaktrivedi** [comment]
These are the nodes we have launched in the EKS managed k8s cluster. Since the pods we are running our experiments on have exact same resource in terms of CPU and memory, and since the experiments majorly benchmark compute capacity of nodes, the individual 4x and 8x large factors don't come into play. Both pods having 1 CPU as request and limit of pod's resources.

**Comment by snadampal** [comment]
Hi @vinayaktrivedi , please try out the instructions I had provided along with AWS DLCs and let us know if you still see any issues.

**Comment by snadampal** [comment]
I'm glad you are able to get the Graviton performance improvements over x86 for BERT model inference!
