### ISSUE TITLE
Cannot run measure_and_plot_basic_sysstat_stats.py

### ISSUE THREAD

**Issue by aldredb** [aws/aws-graviton-getting-started#266]
```
 python3 ./measure_and_plot_basic_sysstat_stats.py --stat cpu-iowait --time 60
Failed to measure statistics with sar.
Please check that sar is installed using install_perfrunbook_dependencies.sh and is in your PATH
Traceback (most recent call last):
  File "/home/ec2-user/aws-graviton-getting-started/perfrunbook/utilities/./measure_and_plot_basic_sysstat_stats.py", line 208, in <module>
    plot(text, stat)
  File "/home/ec2-user/aws-graviton-getting-started/perfrunbook/utilities/./measure_and_plot_basic_sysstat_stats.py", line 117, in plot_cpu
    df = parse_sar(ParseCpuTime, buf)
  File "/home/ec2-user/aws-graviton-getting-started/perfrunbook/utilities/./measure_and_plot_basic_sysstat_stats.py", line 94, in parse_sar
    line = buf.readline()
AttributeError: 'NoneType' object has no attribute 'readline'
```

I have installed the dependencies and i can execute `sar`.

I use AL2 (ami-084237e82d7842286 in us-east-1)

**Comment by geoffreyblake** [comment]
Hi @aldredb 
On your AL2 ami, could you run from the login shell:
```
export S_TIME_FORMAT=ISO
export LC_TIME=ISO
sar -o out.dat -A 1 30
sar -f out.dat -A 1 > out.txt
```
And attach the out.txt here in the ticket?  It may be a new corner case being missed in the parser the script is missing.

**Comment by aldredb** [comment]
@geoffreyblake 

Attached **out.txt** -> [out.txt](https://github.com/aws/aws-graviton-getting-started/files/10772328/out.txt)

Note that there is a warning when setting the `LC_TIME` export
```
[root@ip-172-31-17-166 ~]# export S_TIME_FORMAT=ISO
[root@ip-172-31-17-166 ~]# export LC_TIME=ISO
-bash: warning: setlocale: LC_TIME: cannot change locale (ISO): No such file or directory
-bash: warning: setlocale: LC_TIME: cannot change locale (ISO): No such file or directory
```

**Comment by geoffreyblake** [comment]
Thanks @aldredb , your out.txt looks like it should parse fine, but will take a closer look as getting a no data error usually means a parse error.

**Comment by geoffreyblake** [comment]
@aldredb , I took your out.txt and ran it through the parser manually and it seems to be parsing just fine.  I also started a c6g instance with ami-084237e82d7842286 in us-east-1 and doing
```
git clone https://github.com/aws/aws-graviton-getting-started.git
cd aws-graviton-getting-started/perfrunbook/utilities/
sudo ./install_perfrunbook_dependencies.sh
python3 ./measure_and_plot_basic_sysstat_stats.py --stat cpu-iowait --time 60
```
It ran successfully.  At the moment I cannot reproduce.  Have you reproduced this error recently to give me exact steps to repro and debug?

**Comment by aldredb** [comment]
Turns out `sudo` is required for `python3 ./measure_and_plot_basic_sysstat_stats.py --stat cpu-iowait --time 60
`

![Screenshot 2023-02-24 at 2 38 34 PM](https://user-images.githubusercontent.com/45155724/221109645-41d93f6c-0900-43dd-8950-c087fe73c1dd.png)
