### ISSUE TITLE
bug: EKS cluster running on M7g.large node broke overnight

### ISSUE THREAD

**Issue by zjaco13** [aws/aws-graviton-getting-started#294]
I'm currently working on a graviton pattern in the [cdk-eks-blueprints-patterns](https://github.com/aws-samples/cdk-eks-blueprints-patterns/pull/93) repository, and I left my cluster running overnight with 2 EKS addons, fluxcd and argocd.  

When I went to look this morning, all of my pods were in an unknown state with the one for the aws-node daemonset being in a CrashLoopBackoff.  Yesterday while I was working I had no issues, and I was constantly adding and taking off different addons. 

I have tried scaling up to 3 nodes, but pods are still in unknown state.  The AWS console shows no issues with the cluster or any of the nodes, and there are no issues with the instances in EC2.

**Comment by AWSjswinney** [comment]
This isn't the right place for this issue, but I'll arrange for someone to contact you with some tips.
