### ISSUE TITLE
[c7g.8xlarge] -mcpu=native vs -mcpu=neoverse-512tvb

### ISSUE THREAD

**Issue by xshen053** [aws/aws-graviton-getting-started#316]
Accroding to the guide
https://github.com/aws/aws-graviton-getting-started/blob/main/c-c%2B%2B.md

seems I should use `-mcpu=neoverse-512tvb` if I am using gravtion3 instance to get best performance.
<img width="1118" alt="image" src="https://github.com/aws/aws-graviton-getting-started/assets/97472036/271ce1c0-364d-4892-88cd-87dd1fedf6f8">
But when I run `echo | gcc -E - -mcpu=native -v 2>&1 | grep cc1`, it shows the `-mcpu=native` is 

```
cc1 -E -quiet -v -imultiarch aarch64-linux-gnu - -mlittle-endian -mabi=lp64 -mcpu=zeus+crypto+sha3+sm4+noprofile -fasynchronous-unwind-tables -fstack-protector-strong -Wformat -Wformat-security -fstack-clash-protection -dumpbase -
```

<img width="925" alt="image" src="https://github.com/aws/aws-graviton-getting-started/assets/97472036/b91498d4-2895-465e-92fa-e0da759df356">

https://community.arm.com/arm-community-blogs/b/tools-software-ides-blog/posts/compiler-flags-across-architectures-march-mtune-and-mcpu?_ga=2.125309322.1012238192.1649067243-470348966.1648718387#_ftn3

According to an article from arm, seems -mcpu=native is the better choice, so should I replace `-mcpu=neoverse-512tvb` with '-mcpu=native'?

**Comment by AWSjswinney** [comment]
If you are building for Graviton3 on Graviton3, then yes, using `-mcpu=native` will be fine.

**Comment by xshen053** [comment]
> If you are building for Graviton3 on Graviton3, then yes, using `-mcpu=native` will be fine.

I see, thanks! I will close the issue
