### ISSUE TITLE
Tensorflow Java

### ISSUE THREAD

**Issue by Hexcles** [aws/aws-graviton-getting-started#351]
(Filing this feature request according to https://github.com/aws/aws-graviton-getting-started/blob/main/java.md#looking-for-x86-shared-objects-in-jars)

https://github.com/tensorflow/java claims to support ARM but there's no officially distributed artifacts (JAR) on Maven.

**Comment by Hexcles** [comment]
https://github.com/ARM-software/Tool-Solutions/tree/main/docker/tensorflow-aarch64 only has C++/Python examples, same as https://github.com/aws/aws-graviton-getting-started/blob/main/machinelearning/tensorflow.md

**Comment by snadampal** [comment]
Hi @Hexcles , The official distributed JAR on Mave request  ([tensorflow/java ](https://github.com/tensorflow/java/issues/475)) is currently blocked on github actions supporting aarch64 runners. however, tensorflow java source builds are supported on aarch64 , including mkldnn optimizations ([PR](https://github.com/tensorflow/java/pull/502)). We will update this user guide with the steps.

**Comment by snadampal** [comment]
Hi @Hexcles , we added the source build [instructions](https://github.com/aws/aws-graviton-getting-started/blob/main/machinelearning/tensorflow.md#building-tensorflow-java-from-sources) for TensorFlow java bindings on aarch64 Linux. We hope it unblocks your activity. 

I'm closing the issue.
