### ISSUE TITLE
Pytorch benchmark for Restnet50 with batch size of 1 on Graviton3 worse than on Intel

### ISSUE THREAD

**Issue by saintarian** [aws/aws-graviton-getting-started#355]
I ran the Resnet50 benchmark using instructions provided in this repo [here](https://github.com/aws/aws-graviton-getting-started/blob/d102c0862d4909966b7cb0913607817362c86c5a/machinelearning/pytorch.md). I ran tests on M7g.large and M7i.large instances to compare performance between G3 and Intel. Results are available [here](https://docs.google.com/spreadsheets/d/10_s9bxWc5YCshMvEpxZ6qXwDdJzlN3bnWZuIjgM412g/edit#gid=0). Screenshot of the spreadsheet here: 
![Screen Shot 2024-01-17 at 1 36 01 PM](https://github.com/aws/aws-graviton-getting-started/assets/2073737/8f0b7366-586e-424c-ac39-473381d6b267)

The results show G3 performing ~47% worse than intel on Resnet50 when the batch size is 1 (G3 does better than intel with other models and batch sizes). 

Also worth noting, the instructions to run the test in this repo (linked above) didn't work for me. I had to change:
`python3 run.py Resnet50 -d cpu -m jit -t eval --use_cosine_similarity --bs 32`
to
`python3 run.py Resnet50 -d cpu -t eval --use_cosine_similarity --bs 32`

(I had to remove the `-m jit` flag because it was unrecognized)

**Comment by snadampal** [comment]
Hi @saintarian ,  yes, `-m jit `option is removed in the latest torchbench code, the same can be achieved with `--backend torchscript` option now. We will update the user guide as part of PyTorch 2.2 updates coming in February.

Regarding the resnet50 performance with batchsize=1,  single client, single inference test is purely a micro benchmark, I think it will not utilize more than 10-15% cpu. Can you please try with multiple clients, each doing single batch inferences to make it more like a real use case? also try enabling the torchscript backend with the above option.

**Comment by saintarian** [comment]
Thanks @snadampal - I'll get back to you with updated numbers using `--backend torchscript`. I'll also check cpu usage using htop while running resnet50 with batchsize=1 and single client. OOC, is there something specific about resnet50 that makes the single-client batchsize=1 scenario perform worse than the same configuration for BERT and Clip? BERT and Clip with batchsize=1 perform ~34% better on G3 than on intel.

**Comment by snadampal** [comment]
resnet50 is 25M params model whereas bert base is 110M and bert large is 330M params models. It's just that the tensor shapes are smaller in resnet50 compared to bert, hence it's less compute intensive.
btw, torchbench uses batchsize=32 for resnet50 and batchsize=2 for bert as the default configs which makes sense from loading point of view.

**Comment by saintarian** [comment]
Make sense. Closing this issue. @snadampal - while I have you, do you know why single-batch clip (model called `torch_multimodal_clip` in the benchmark) takes so long (almost as long as 16-batch)?

**Comment by snadampal** [comment]
@saintarian, please enable DNNL logs and check if any of the shapes are using the onednn `c` reference kernels instead of Arm compute library kernels. to enable logs 

`export DNNL_VERBOSE=1`

you can refer to the troubleshooting section to know how to interpret the DNNL logs.
https://github.com/aws/aws-graviton-getting-started/blob/main/machinelearning/pytorch.md#troubleshooting-performance-issues
