### ISSUE TITLE
c6g specifics within machinelearning/pytorch.md

### ISSUE THREAD

**Issue by FireballDWF** [aws/aws-graviton-getting-started#369]
While machinelearning/pytorch.md has specifics for graviton3 based instances types, having details specific to graviton2 would help customers using the c6g instance types available on the 1u form factor of Outposts Servers.  graviton3 is not available for Outposts Servers, thus customers with ml inference use cases that need to deploy to "The Edge" and choose Outposts servers, need optimization details for graviton2. 

I did a little research which found the following might be applicable, but hoping experts can weigh in.
export DNNL_DEFAULT_FPMATH_MODE=ANY

**Comment by snadampal** [comment]
Hi @FireballDWF , the PyTorch user guide is equally applicable to `Graviton2` and `Graviton3`. But I agree with you,  because we highlighted `Graviton3` ML features (`BFloat16`) in the doc, it might give impression that the steps are only applicable to it. We will fix it. 
btw, `DNNL_DEFAULT_FPMATH_MODE=ANY` behaves the same way as `DNNL_DEFAULT_FPMATH_MODE=BF16` on `Graviton3` and this has no effect on `Graviton2`.

**Comment by FireballDWF** [comment]
Are Graviton2's "Half-precision floating-point data processing" aka fphp automatically used? Or need to enable the option? Not used as would not improve the speed? Not used because no one has tried implementation of using these instructions?

**Comment by snadampal** [comment]
It depends on the framework. for example, [MNN](https://github.com/alibaba/MNN) supports fp16 kernels, and we [enabled](https://github.com/alibaba/MNN/pull/1821) them for Graviton (starting from 2). Whereas PyTorch and TensorFlow use oneDNN (aka DNNL or MKLDNN) and we prioritized bf16 fastmath over fp16 for aarch64 here.
I will reach out to you to better understand the need for FP16 fast math kernels for Graviton in PyTorch.

**Comment by geoffreyblake** [comment]
@FireballDWF , @snadampal , did you two connect outside this issue?  If so, can this issue be closed and what was the outcome?

**Comment by FireballDWF** [comment]
As Hybrid Edge scenarios which use Local Zones and Outposts, both of which only currently support Graviton2 based 6th gen instance types, until the Graviton3 based 7th gen instance types are supported in these locations, either is no oppt to use Graviton3 in these edge environments.

**Comment by snadampal** [comment]
Hi @FireballDWF as we discussed offline, i'm closing this ticket.
