### ISSUE TITLE
ECS Exit code: 132 on Graviton3

### ISSUE THREAD

**Issue by Smotrov** [aws/aws-graviton-getting-started#370]
I running my app written in Rust on ECS backed by Graviton3 EC2. It runs as expected.

After my attempt to optimize compilation using processor specific things `RUSTFLAGS="-C target-cpu=neoverse-v1 -C target-feature=+sve2,+lse"` the app starts even prints some Wellcome output and stops with Exit code: 132.

I started separate EC2 with Graviton3 processor. Installed Docker there and same app with same dokerfile works there like a charm. 

Meanwhile, if I switch neoverse-v1 (which supposed to be supported by G3) to neoverse-n1 it works on ECS. 

Is there some additional tuning required to use +sve2,+lse on ECS?

**Comment by AGSaidi** [comment]
Graviton3 supports sve, not sve2

**Comment by Smotrov** [comment]
Thank you @AGSaidi, you absolutely right. 
Unfortunately ` RUSTFLAGS="-C target-cpu=neoverse-v1 -C target-feature=+sve,+lse"` on ECS backed by M7G shows Exit code: 132 as well. Which is actually SIGILL.

**Comment by Smotrov** [comment]
Even without mentioning features. It fails on ECS with `RUSTFLAGS="-C target-cpu=neoverse-v1"` and works well with `RUSTFLAGS="-C target-cpu=neoverse-n1"`. Which is strange.

**Comment by geoffreyblake** [comment]
@Smotrov , how do you create the ECS cluster?  Do you create it using on-demand EC2 instances?

If you pick Amazon Linux 2 (arm64) you will get an old 4.14 kernel that does not support SVE on 7g and you will see this crash.  You need to get a kernel that is 5.4+, so Amazon Linux 2 (5.10/arm64), Amazon Linux 2023 (arm64) and Bottlerocket (6.1/arm64) should all have the required support to run SVE binaries.

**Comment by sreedharamzn** [comment]
@Smotrov: Did your attempts to optimize compilation on any of Amazon Linux 2 (5.10/arm64), Amazon Linux 2023 (arm64) or Bottlerocket (6.1/arm64) succeed?
Can we close this ticket?

**Comment by Smotrov** [comment]
My base for this apps is 
```
FROM --platform=linux/arm64  amazonlinux:2023
```

**Comment by geoffreyblake** [comment]
That is your container base image @Smotrov , can you tell us what the container host OS is?   That will provide the information on the kernel being used to host the containers.

**Comment by Smotrov** [comment]
I see. ECS is using following machine image  `amzn2-ami-ecs-hvm-2.0.20240409-arm64-ebs`

**Comment by geoffreyblake** [comment]
Thanks @Smotrov , that AMI will be using the really old 4.14 kernel.  You need your ECS cluster to use `amzn2-ami-ecs-kernel-5.10-hvm-2.0.20240409-arm64-ebs` to get the updated kernel that supports SVE for Gv3.

**Comment by Smotrov** [comment]
@geoffreyblake  thank you! Will try and come back with report. This is actually what is CDK defaulted to.

**Comment by Smotrov** [comment]
@geoffreyblake thank you very much! 
It dies help. 
Works like a charm with `amazon/al2023-ami-ecs-hvm-2023.0.20240409-kernel-6.1-arm64`
