### ISSUE TITLE
read and write msr

### ISSUE THREAD

**Issue by hilldani** [aws/aws-graviton-getting-started#375]
This guide explains PMU's but nothing about MSR's. I would like to test the impact of certain MSR's. Is there a recommended method similar to x86's rdmsr and wrmsr?

**Comment by JulianMarcusSchroeder** [comment]
Are you wanting to access [system registers](https://developer.arm.com/documentation/den0024/a/ARMv8-Registers/System-registers)? What specifically do you want to do?
