### ISSUE TITLE
Chrome missing for arm64

### ISSUE THREAD

**Issue by np-ally** [aws/aws-graviton-getting-started#41]
Nafea Bshara said to post here if we had any issues. Looks like Google only releases Chrome for Linux on amd architecture, no arm64. Only Chromium is available on arm64. We will see if we can use chromium as a part of our application, but thought to highlight this gap. Others may have the same issue.

**Comment by AGSaidi** [comment]
Yea, we know it's an issue that they don't vend arm64 artifacts. One workaround is to use a debian container with the chromium package installed. Would that work for your use case? Both Ubuntu and Debian do have packages for chrome.

**Comment by np-ally** [comment]
Not sure yet, as stated above, we are checking if chromium can satisfy our use case. We have a few use cases for it. Yes, we are trying this on Ubuntu 20.04

**Comment by lizthegrey** [comment]
With Chromium no longer including Chrome Sync, this is now resufacing as an issue, as Chromium will no longer be able to include the most common workflows expected from Chrome linux.

**Comment by AGSaidi** [comment]
@lizthegrey if you have any ideas, please let me know.

**Comment by lizthegrey** [comment]
> @lizthegrey if you have any ideas, please let me know.

Lobbying the Google Chrome team to release an official ARM64 build. They already do it for ChromeOS so...

**Comment by csvan** [comment]
Hate to necro this, but are there ANY new developments on this front? The lack of arm64 support is a glaring hole especially for users of AWS Graviton instances. I have not been able to find any unofficial builds that work either.

**Comment by lizthegrey** [comment]
> Hate to necro this, but are there ANY new developments on this front? The lack of arm64 support is a glaring hole especially for users of AWS Graviton instances. I have not been able to find any unofficial builds that work either.

For now, using the chromium Snap for Ubuntu largely works minus the Chrome Sync issue.

You could also try to extract the Chrome binary from a ChromeOS image...
