### ISSUE TITLE
How to use `perf c2c` on Graviton 3 ? (Larger than m7g.16xlarge)? 

### ISSUE THREAD

**Issue by FabianSchuetze** [aws/aws-graviton-getting-started#415]
Thanks for the performance guide. 

How can I run `perf c2c record`  on an aws m7g.16xlarge instance? 

When I run it, I get:
```
ubuntu@ip-172-31-19-137:~$ sudo perf c2c record ./a.out 
failed: memory events not supported
```
The linux version is:
```
ubuntu@ip-172-31-19-137:~$ uname -a
Linux ip-172-31-19-137 6.8.0-1012-aws #13-Ubuntu SMP Mon Jul 15 15:42:27 UTC 2024 aarch64 aarch64 aarch64 GNU/Linux
```
Base on the [docs](https://github.com/aws/aws-graviton-getting-started/blob/main/perfrunbook/debug_hw_perf.md#how-to-collect-pmu-counters) I have use 16xlarge machine. The man pages for `perf c2c record` say:
>  On Arm64 it uses SPE to sample load and store operations, therefore hardware and kernel support  is required. See perf-arm-spe(1) for a setup guide. Due to the statistical nature of Arm SPE sampling, not every memory operation will be sampled.
 

The ARM [docs](https://developer.arm.com/documentation/101136/22-1-3/MAP/Arm-Statistical-Profiling-Extension--SPE-/SPE-Prerequisites) say about `spe` that events need to be visible at `sys/bus/event_source/devices/arm_spe_XX.`, which is not a valid path on my machine.

How can I use `perf c2c record` on an m7g.16xlarge instance?

**Comment by AGSaidi** [comment]
SPE is only available on metal instances. You’d need to use m7g.metal (which has the same number of CPUs) and load the SPE driver.

**Comment by FabianSchuetze** [comment]
Thanks for the comment. I misunderstood the necessity of using bare metal.

Can you explain to me how I can install and load the SPE driver?

I did (based on: https://repost.aws/questions/QUszjkFC_6TEqFKZKlOvKc8g/arm-bare-metal-servers ):
- sudo apt-get install linux-modules-extra-$(uname -r)
- sudo modprobe arm_spe_pmu 

There was no confirmation or any info after I've done `modprobe..` . I still don't see anything at `sys/bus/event_source/devices/arm_spe_XX` or at ` /sys/devices/arm_spe_0`.

**Comment by FabianSchuetze** [comment]
Can you tell me how I can do that?

**Comment by nafeabd** [comment]
Can you add those options to GRUB_CMDLINE_LINUX and try it? The options passed to GRUB_CMDLINE_LINUX_DEFAULT will only propagate to default kernel and if you have multiple kernels installed they won't propagate to all kernels.

**Comment by FabianSchuetze** [comment]
Thanks for the comment. That solved the problem.
