### ISSUE TITLE
Typo in recommended -march compiler flag

### ISSUE THREAD

**Issue by srgsanky** [aws/aws-graviton-getting-started#424]
Is `-march=armv8.2a` missing a `-`. This needs to be `-march=armv8.2-a`.

https://github.com/aws/aws-graviton-getting-started/blob/0643401ea8e40a18ab9d2845ae3966d46581d13d/perfrunbook/configuring_your_sut.md?plain=1#L138

```
cc1: error: unknown value 'armv8.2a' for -march
cc1: note: valid arguments are: armv8-a armv8.1-a armv8.2-a armv8.3-a armv8.4-a; did you mean 'armv8.2-a'?
```

**Comment by AWSNB** [comment]
good callout,  thank you, will fix
