### ISSUE TITLE
Please document Linux kernel kconfig options for ARM errata workarounds

### ISSUE THREAD

**Issue by joshtriplett** [aws/aws-graviton-getting-started#430]
The Linux kernel has a whole family of configuration options for various ARM errata workarounds; see https://www.kernel.org/doc/html/latest/arch/arm64/silicon-errata.html and `arch/arm64/Kconfig` under `menu "ARM errata workarounds via the alternatives framework"`.

Please consider documenting which of these apply to Graviton 4 (and forward), so that people building Linux kernels specifically for c8g and newer can turn off all unnecessary errata workaround code.

**Comment by geoffreyblake** [comment]
Hi @joshtriplett , all Graviton CPUs use standard cores from the Arm Neoverse line and we have the required MIDR information so the kernel can dynamically select and apply the relevant Errata at runtime.  If you really want to customize your kernel build, then the relevant errata for Neoverse-N1 (Graviton2), Neoverse-V1 (Graviton3) and Neoverse-V2 (Graviton4) apply, but I wouldn't recommend doing so.
