### ISSUE TITLE
graviton2 instance family should be disabled when the Centos 7 AMI is selected.

### ISSUE THREAD

**Issue by ensean** [aws/aws-graviton-getting-started#62]
As describe in the [doc](https://github.com/aws/aws-graviton-getting-started/blob/master/os.md), Centos 7 is not supported by Graviton2. 

But when launching instance, once the Centos 7 AMI is chosen, the graviton2 instance types can be selected. This is quite confused which may cause customer to run Centos 7 on graviton 2 instances...

**Comment by AGSaidi** [comment]
Yes, we realize it can be confusing. Some customers have chosen to run Centos 7 even though it's not officially supported. We don't want to prevent people from doing this, but RHEL and CentOS 8.2 and onward are the only supported OSes on Graviton2

**Comment by JeffUnderhill** [comment]
For specific OS versions supported on Graviton2 refer to the [Operating Systems](https://github.com/aws/aws-graviton-getting-started/blob/master/os.md) section of this guide.
