### ISSUE TITLE
Amazon Linux 2 gcc doesn't support -march flags

### ISSUE THREAD

**Issue by entonos** [aws/aws-graviton-getting-started#72]
Using the current Amazon Linux 2 AMI and pulling gcc (i.e. sudo yum groupinstall -y "Development tools"), that version of gcc doesn't support -march=armv8.2-a+fp16+rcpc+dotprod+crypto (as suggested from https://github.com/aws/aws-graviton-getting-started/blob/master/c-c%2B%2B.md). it will accept -march=armv8.2-a+fp16+crypto.

**Comment by sebpop** [comment]
AL2 distributes gcc-7 which does not have rcpc and dotprod. The GNU assembler in binutils 2.29 distributed by AL2 has support for these instructions, so you can use these instructions on AL2 by writing inline assembly.
I am working on adding a newer gcc-10 to AL2 to allow the use of these instructions from the compiler.

**Comment by sebpop** [comment]
I added a note to clarify that gcc-7 does not support the instructions: https://github.com/aws/aws-graviton-getting-started/pull/73

**Comment by entonos** [comment]
Thanks for the info. Close if you like.
