### ISSUE TITLE
Processor extension for Graviton2

### ISSUE THREAD

**Issue by afernandezody** [aws/aws-graviton-getting-started#75]
Hello,
This is sort of a blend between a quick question and an issue as nothing is actually broken. The assumption is that Graviton2 is a Neoverse N1 processor with an Armv8.2-A implementation as mentioned in README and other documents. However, GNU is reporting the architecture to be Armv8-A without specifying any extension. My doubt is why of this discrepancy. The two most obvious explanations are: (i) Graviton2 does not fully implement Armv8.2-A and GNU thus uses a more generic implementation; (ii) Graviton2 is a full Armv8.2-A implementation and GNU, for some reason, is not recognizing it. Maybe there is a 3rd explanation that I don't see. Thanks.

**Comment by AGSaidi** [comment]
older versions of GCC don't have the proper detection code enabled. What compiler version are you using? from a distro?

**Comment by afernandezody** [comment]
I'm using Ubuntu 20.04 and the GNU version (I think) is 9.3.0.

**Comment by AGSaidi** [comment]
We'll take a look and when the  patches to detect Neoverse-N1 ended up in GCC9 and what we can do to address this. You can manually specify the features listed [here](https://github.com/aws/aws-graviton-getting-started/blob/master/c-c%2B%2B.md) in the mean time. Graviton2 supports the full v8.2-a implementation plus select features from newer revisions.

**Comment by csoma** [comment]
Not sure if I understand this issue correctly. Using GCC 9 with the '-march' flag the architecture is not detected correctly?

Here is what I tried:

```
sudo apt-get -y install build-essential
cat /etc/os-release | grep PRETTY_NAME
	Ubuntu 20.04.1 LTS

gcc --version
	gcc (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0

make --version
	GNU Make 4.2.1 Built for aarch64-unknown-linux-gnu

ldconfig --version
	ldconfig (Ubuntu GLIBC 2.31-0ubuntu9.1) 2.31

gcc -march=native -Q --help=target
  -mabi=                      		lp64
  -march=                     		armv8.2-a+crypto+fp16+rcpc+dotprod
  -mbig-endian                		[disabled]
  -mbionic                    		[disabled]
  -mbranch-protection=        		
  -mcmodel=                   		small
  -mcpu=                      		generic
  -mfix-cortex-a53-835769     		[enabled]
  -mfix-cortex-a53-843419     		[enabled]
  -mgeneral-regs-only         		[disabled]
  -mglibc                     		[enabled]
  -mharden-sls=               		
  -mlittle-endian             		[enabled]
  -mlow-precision-div         		[disabled]
  -mlow-precision-recip-sqrt  		[disabled]
  -mlow-precision-sqrt        		[disabled]
  -mmusl                      		[disabled]
  -momit-leaf-frame-pointer   		[enabled]
  -moutline-atomics           		[disabled]
  -moverride=<string>         		
  -mpc-relative-literal-loads 		[enabled]
  -msign-return-address=      		none
  -mstack-protector-guard-offset= 	
  -mstack-protector-guard-reg= 		
  -mstack-protector-guard=    		global
  -mstrict-align              		[disabled]
  -msve-vector-bits=<number>  		scalable
  -mtls-dialect=              		desc
  -mtls-size=                 		24
  -mtrack-speculation         		[disabled]
  -mtune=                     		generic
  -muclibc                    		[disabled]
  -mverbose-cost-dump         		[disabled]
```

This is the same flag list as specified in the [Graviton Getting Started guide](https://github.com/aws/aws-graviton-getting-started/blob/master/c-c%2B%2B.md).

**Comment by sebpop** [comment]
@afernandezody could you please let us know which command or program you used to identify that "GNU is reporting the architecture to be Armv8-A without specifying any extension"?
There may be an underlying issue that we are not seeing.

Thanks for your bug report!

**Comment by afernandezody** [comment]
Actually, I noticed it while using the assembler (for both gcc & gfortran). If I simply try `gcc -S example.c`, the assembly code reads
```
        .arch armv8-a
        .file   "ex1.c"
        .text
        .section        .rodata
        .align  3
        ...
```
Thus far I've been using -march=native for compilation purposes (assuming that this would be optimal). However, I'm trying to dig a bit deeper in some aspects by using the assembler, which led me to the question. It might be nothing but the assembly code outcome surprised me earlier today.

**Comment by afernandezody** [comment]
OK. If I add `-march=native`, it yields `.arch armv8.2-a+crypto+crc+fp16+rcpc+dotprod`. (I also tried `-march=armv8.2-a` that uses `.arch armv8.2-a+crc` without crypto, fp16, rcpc, dotprod). Everything is fine, it's just a matter of using `-march=native` even for very small codes. Thanks.

**Comment by csoma** [comment]
fp16, dotprod and the others are optional, not all v8.2-a implementations have them - for this reason it has to be added explicitly.
