### ISSUE TITLE
PHP80 not included in amzn2-extras.repo

### ISSUE THREAD

**Issue by ensean** [aws/aws-graviton-getting-started#82]
PHP80 not included in amzn2-extras.repo which make it hard for users to install php8.0 on Amazon Linux2 to enjoy the performance improvement brings by php8.0

**Comment by AWSNB** [comment]
i believe this was updated in AL2 earlier this year, with 8.0.2 released already and 8.0.6 coming soon

i'll close this ticket, and @ensean  - feel free to re-open it if you think its not available or not working right

**Comment by ensean** [comment]
Yep, I can install php 8.0.6 with amazon-linux-extras now.
